@category = N_("Toolkit")
@name = N_("RabbitHeadlineLogo")
@abstract = N_("Toolkit to display Lavie at the headlines")
@description = N_("Displays Lavie at the headlines of slides.")
@dependencies = %w(rabbit-images headline-logo)
