@category = N_("Toolkit")
@name = N_("RabbitHeadlineLogo")
@abstract = N_("Toolkit to display Lavie as a logo at the headlines")
@description = N_("Displays Lavie as a logo at the headlines of slides.")
@dependencies = %w(rabbit-images headline-logo)
